### ISSUE TITLE
Anyone with problems? ->Miflora Firmware 3.3.5

### ISSUE THREAD

**Issue by Firepower** [ThomDietrich/miflora-mqtt-daemon#150]
Hello, 

my sensor worked fine in the past but since updating firmware to 3.3.5 it's not working anymore.
`Dec 16 06:41:49 raspberrypi systemd[1]: miflora.service: Succeeded.
Dec 16 06:41:49 raspberrypi systemd[1]: Stopped Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon.
Dec 16 06:41:49 raspberrypi systemd[1]: Starting Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon...
Dec 16 06:41:50 raspberrypi systemd[1]: Started Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon.
Dec 16 06:41:51 raspberrypi python3[2312]: [2021-12-16 06:41:51] Initial connection to Mi Flora sensor "Pflanze" (XX:XX:XX:XX:XX:XX) failed due to exception:
Dec 16 06:41:51 raspberrypi python3[2312]: [2021-12-16 06:41:51] Failed to retrieve data from Mi Flora sensor "Pflanze" (XX:XX:XX:XX:XX:XX), success rate: 0%
`
MiFlora-Smartphone app connects as usual but miflora-mqtt-deamon is not working anymore.

Does anyone encounter the same problem? Especially with firmware 3.3.5? 

regards,
Thomas

**Comment by Firepower** [comment]
Strange, tried different things, none of these worked. Yesterday I had to restart my pi and now its working. So my issue is resolved ;-)

**Comment by ThomDietrich** [comment]
Strange but relieved there is no new issue. I will mention your firmware 3.3.5 in the README as tested. Thanks!

**Comment by jorgnyg** [comment]
@ThomDietrich @Firepower I'm getting the same error when running docker.
It connects successfully with `python3 /opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py`,
but running `docker run -it --name miflora-mqtt-daemon -v /opt/miflora-mqtt-daemon/config.ini:/config/config.ini miflora-mqtt-daemon` results in:
```
[2022-01-08 10:12:58] Initial connection to Mi Flora sensor "Chili" (C4:7C:8D:6C:94:33) failed due to exception: 
[2022-01-08 10:12:58] Announcing Mi Flora devices to MQTT broker for auto-discovery ...
[2022-01-08 10:12:58] Retrieving data from sensor "Chili" ...
[2022-01-08 10:12:59] Retrying ...
[2022-01-08 10:12:59] Failed to retrieve data from Mi Flora sensor "Chili" (C4:7C:8D:6C:94:33), success rate: 0%
```

Config file is mounted correctly, since changes in config file (like device name) is correctly reflected in log output. Could have something to do with access to bluetooth interface when running with docker or something?

**Comment by Firepower** [comment]
@jorgnyg This is the same problem i had. After some restarts of my raspberry pi it worked again. Before that I tried to restart miflora.service which didn't work. Since then its running fine.
